DROP TABLE USERS IF EXISTS;
DROP TABLE POSTS IF EXISTS;
DROP TABLE COMMENTS IF EXISTS;
CREATE TABLE USERS(
   USER_ID VARCHAR(64) PRIMARY KEY,
   NAME VARCHAR(255)
);
CREATE TABLE POSTS (
   POST_ID VARCHAR(64) PRIMARY KEY,
   USER_ID VARCHAR(64),
   CREATED DATETIME,
   TEXT LONGVARCHAR,
   FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);
CREATE TABLE COMMENTS (
   COMMENT_ID VARCHAR(64) PRIMARY KEY,
   POST_ID VARCHAR(64),
   CREATED DATETIME,
   TEXT VARCHAR(255),
   FOREIGN KEY(POST_ID) REFERENCES POSTS(POST_ID)
);
